### PR TITLE
md5

### PR DESCRIPTION
**Pull request by marvhus**
Still a work in progress, but I'm pull requesting what I have so far.

I added the functionality to get the md5 of a string using hashlib.
And the functionality to "crack" it using a wordlist.

### CODE REVIEW

**Comment by marvhus** [comment]
(The issue is not done yet, I just wanted to add what I had so far)

**Review by AlexKollar — CHANGES_REQUESTED** [review]
Add any and all pycaches from here in to git ignore. Aside of that looking good 😉

I remember how epically proud I was when I did the first md5 cracker.💪🏻🧐💪🏻

**Comment by marvhus** [comment]
> Add any and all pycaches from here in to git ignore. Aside of that looking good wink
> 
> I remember how epically proud I was when I did the first md5 cracker.💪🏻monocle_face💪🏻

I tried that yesterday on a different branch, but I didn't get it to work, but ill try again

**Comment by marvhus** [comment]
> > Add any and all pycaches from here in to git ignore. Aside of that looking good wink
> > I remember how epically proud I was when I did the first md5 cracker.💪🏻monocle_face💪🏻
> 
> I tried that yesterday on a different branch, but I didn't get it to work, but ill try again

Fixed it, I had to remove the files (using `find . -name "*.pyc" -exec git rm -f "{}" \;`) and add them to the gitignore, not just add it to the .gitignore

**Pull request merged**
